const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const root=path.resolve(__dirname,'../..'), out=path.resolve(__dirname,'..');
const excluded=new Set(['node_modules','.git','dist','build','coverage','.cache','.vite','.vite-temp','watsolution_web_reportes']);
function walk(dir='',files=[],dirs=[],skip=[]){for(const e of fs.readdirSync(path.join(root,dir),{withFileTypes:true})){const p=dir?dir+'/'+e.name:e.name;if(e.isDirectory()){if(excluded.has(e.name)){skip.push(p);continue;}dirs.push(p);walk(p,files,dirs,skip);}else if(e.isFile())files.push(p);}return {files,dirs,skip};}
function redact(s){return s.replace(/(\b(?:password|secret|token|apiKey|api_key|accessKeyId|secretAccessKey|base64-secret|jwtSecret)\b\s*[:=]\s*)(["'])([^\r\n]*?)\2/gi,(m,p,q,v)=>v.includes('${')||v.includes('process.env')?m:p+q+'[ENMASCARADO]'+q).replace(/(postgres(?:ql)?:\/\/[^:\s]+:)[^@\s]+@/gi,'$1[ENMASCARADO]@').replace(/\b(?:sk-(?:proj-)?[\w-]{16,}|AKIA[A-Z0-9]{16}|ghp_[\w]{20,})\b/g,'[ENMASCARADO]');}
const mode=process.argv[2];
if(mode==='inventory') {const inv=walk();inv.entries=inv.files.map(p=>{const b=fs.readFileSync(path.join(root,p));return {path:p,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex'),lines:b.includes(0)?null:b.toString('utf8').split(/\r?\n/).length,state:'no revisado',notes:'Lectura y análisis por realizar'};});fs.writeFileSync(path.join(out,'evidencias/inventario-inicial.json'),JSON.stringify(inv,null,2));fs.writeFileSync(path.join(out,'evidencias/git-status-inicial.txt'),cp.execFileSync('git',['status','--porcelain=v1'],{cwd:root,encoding:'utf8'}));fs.writeFileSync(path.join(out,'00_cobertura.md'),'# Cobertura de auditoría\n\nEstado inicial. Los cambios locales preexistentes forman parte del alcance.\n\nExclusiones: '+inv.skip.join(', ')+'\n\n| Archivo | Categoría | Estado | Notas |\n|---|---|---|---|\n'+inv.entries.map(e=>`| ${e.path} | ${e.path.split('/')[0]} | ${e.state} | ${e.bytes} bytes; ${e.lines??'binario'} líneas |`).join('\n'));console.log(JSON.stringify({files:inv.files.length,dirs:inv.dirs.length,skip:inv.skip,lines:inv.entries.reduce((s,e)=>s+(e.lines||0),0),largest:inv.entries.sort((a,b)=>b.bytes-a.bytes).slice(0,12)},null,2));}
if(mode==='read'){const inv=JSON.parse(fs.readFileSync(path.join(out,'evidencias/inventario-inicial.json')));const re=new RegExp(process.argv[3]);for(const p of inv.files.filter(x=>re.test(x))){const b=fs.readFileSync(path.join(root,p));if(b.includes(0)){console.log(p+' [binario '+b.length+' bytes]');continue;}const text=redact(b.toString('utf8'));console.log('\n### '+p+'\n'+text.split(/\r?\n/).map((l,i)=>`${i+1}: ${l}`).join('\n'));}}
if(mode==='section'){const p=process.argv[3],start=Number(process.argv[4]||1),end=Number(process.argv[5]||1e9);const text=redact(fs.readFileSync(path.join(root,p),'utf8'));console.log('### '+p);console.log(text.split(/\r?\n/).map((l,i)=>`${i+1}: ${l}`).slice(start-1,end).join('\n'));}
if(mode==='vue'){const inv=JSON.parse(fs.readFileSync(path.join(out,'evidencias/inventario-inicial.json')));for(const p of inv.files.filter(p=>p.endsWith('.vue')&&new RegExp(process.argv[3]).test(p))){const txt=redact(fs.readFileSync(path.join(root,p),'utf8'));console.log('### '+p);let inside=false;console.log(txt.split(/\r?\n/).map((l,i)=>{if(l.includes('<script'))inside=true;const v=inside?`${i+1}: ${l}`:null;if(l.includes('</script>'))inside=false;return v;}).filter(Boolean).join('\n'));}}
module.exports={root,out,walk,redact};
