const {root,out,walk}=require('./audit-tools.cjs'),fs=require('fs'),path=require('path'),cp=require('child_process'),zlib=require('zlib');const ev=path.join(out,'evidencias');
const exec=(args)=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8',maxBuffer:64*1024*1024,windowsHide:true});
// Scan all reachable historic blobs locally. No raw values are printed or saved.
const objects=exec(['rev-list','--objects','--all']).trim().split('\n').map(x=>{const i=x.indexOf(' ');return{oid:i<0?x:x.slice(0,i),path:i<0?'':x.slice(i+1)}}).filter(x=>x.path&&!/(node_modules|\.png$|\.ico$|\.svg$|package-lock\.json$)/.test(x.path));
const candidate=objects.filter(o=>/\.(env|[cm]?ts|js|json|ya?ml|toml|md|pem|key)$|(?:^|\/)\.env(?:\.|$)/i.test(o.path)),historical=[];let scanned=0;
for(const o of candidate){let content;try{content=exec(['cat-file','blob',o.oid]);}catch{continue;}scanned++;for(const [i,l]of content.split(/\r?\n/).entries()){if(/(?:base64-secret|JWT_SECRET|api.?key|secret.?key|secretAccessKey|accessKeyId|password)\s*['"]?\s*[:=]\s*['"]?\S/i.test(l)&&!/(process\.env|\$\{|@|interface|\?:|description:|readonly|password: string|password: unknown)/.test(l)&&!/^\s*(\/\/|#|\*|import)/.test(l)){historical.push({object:o.oid,path:o.path,line:i+1,kind:'Literal relacionado con credenciales; valor ENMASCARADO, requiere clasificación'});}if(/BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY|\bAKIA[A-Z0-9]{16}|sk-proj-[\w-]{20,}/.test(l))historical.push({object:o.oid,path:o.path,line:i+1,kind:'Patrón de secreto; ENMASCARADO'});}}
const commits=exec(['rev-list','--count','--all']).trim();fs.writeFileSync(path.join(ev,'secretos-historial.json'),JSON.stringify({commits,blobsScanned:scanned,candidates:historical,limitations:'Detección heurística de literales. No consulta validez ni prueba credenciales. Objetos inalcanzables y remotos no descargados fuera de alcance.'},null,2));
const lint={};for(const name of ['lintserver','lintclient']){const p=path.join(ev,name+'.log');try{const data=JSON.parse(fs.readFileSync(p,'utf8'));const byRule={};for(const f of data){for(const m of f.messages){byRule[m.ruleId||'parse']=(byRule[m.ruleId||'parse']||0)+1;delete m.fix;delete m.suggestions;}delete f.source;}fs.writeFileSync(p,JSON.stringify(data,null,2));lint[name]={files:data.length,errors:data.reduce((n,f)=>n+f.errorCount,0),warnings:data.reduce((n,f)=>n+f.warningCount,0),byRule};}catch(e){lint[name]={error:e.message};}}
const assets=[];function inspect(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())inspect(p);else{const b=fs.readFileSync(p);assets.push({path:path.relative(ev,p).replaceAll('\\','/'),bytes:b.length,gzip:zlib.gzipSync(b).length});}}}inspect(path.join(ev,'build'));
fs.writeFileSync(path.join(ev,'build-inventario.json'),JSON.stringify(assets,null,2));fs.writeFileSync(path.join(ev,'lint-resumen.json'),JSON.stringify(lint,null,2));
console.log(JSON.stringify({commits,blobsScanned:scanned,secretCandidates:historical.length,interesting:historical.filter(h=>/application.yml|\.env|\.yo-rc|orm.config/.test(h.path)).slice(0,20),lint,build:{files:assets.length,totalBytes:assets.reduce((s,a)=>s+a.bytes,0),robots:assets.some(a=>a.path.endsWith('robots.txt')),manifest:assets.some(a=>a.path.endsWith('manifest.webapp')),largest:assets.sort((a,b)=>b.bytes-a.bytes).slice(0,6)}},null,2));
