const {root,out}=require('./audit-tools.cjs'),fs=require('fs'),path=require('path'),assert=require('assert');
process.env.BACKEND_ENV='test';require('ts-node').register({project:path.join(root,'server/tsconfig.json'),transpileOnly:true});require('reflect-metadata');
const load=p=>require(path.join(root,p));
(async()=>{const results=[];
 const {PortalService}=load('server/src/service/portal.service.ts');
 const victim={id:7,userId:'42',email:'victim@example.invalid',fullName:'Synthetic victim',status:'ACTIVE'};
 let query;
 const people={findOne:async opts=>{query=opts.where;return opts.where.some(c=>c.userId===victim.userId||c.email===victim.email)?victim:null;}};
 const qb={innerJoin(){return this},select(){return this},where(){return this},andWhere(){return this},getRawOne:async()=>({total:0})};
 const invoices={find:async()=>[],findOne:async()=>null},meters={findOne:async()=>null,createQueryBuilder:()=>qb};
 const portal=new PortalService(people,invoices,meters);const data=await portal.getPortalData('42');
 assert.equal(data.person.userId,'42');results.push({test:'Portal selecciona persona de cuenta 42 para un login literal 42; el controlador no pasa el ID autenticado 99',result:'Confirmado con repositorios simulados',authenticatedUser:{id:99,login:'42'},query,returnedPersonOwner:data.person.userId});
 const {InvoiceController}=load('server/src/web/rest/invoice.controller.ts'),{InvoiceService}=load('server/src/service/invoice.service.ts');
 let row={id:1,status:'PENDING',amountDue:100,consumptionM3:1,issueDate:'2026-01-01',dueDate:'2026-01-31',person:{id:7,userId:'42'}};
 const repo={findOne:async()=>structuredClone(row),save:async entity=>{row={...row,...entity};return structuredClone(row)}};
 const svc=new InvoiceService(repo,{save:async()=>{}},{findOne:async()=>null},{send:async()=>{}});
 const controller=new InvoiceController(svc,{generate:async()=>Buffer.from('synthetic-pdf')},{uploadPdf:async()=>{row.status='PAID';row.boldTransactionId='synthetic-payment';},getPresignedUrl:async()=> 'https://example.invalid/synthetic'},{});
 await controller.getDownloadUrl(1);assert.equal(row.status,'PENDING');results.push({test:'Descarga PDF sobrescribe un pago confirmado durante la subida',result:'Confirmado con intercalado simulado de repositorio y S3',statusAfterPayment:'PAID',statusAfterDownload:row.status});
 const {BoldService}=load('server/src/service/bold.service.ts');process.env.BOLD_SECRET_KEY='synthetic-audit';process.env.BOLD_API_KEY='synthetic-audit';
 let order;const bold=new BoldService({findOne:async()=>({id:1,status:'PENDING',amountDue:100,boldOrderId:null}),update:async(_,v)=>{order=v.boldOrderId;}},{},{},{});
 const [a,b]=await Promise.all([bold.getHashForInvoice(1),bold.getHashForInvoice(1)]);assert.notEqual(a.boldOrderId,b.boldOrderId);results.push({test:'Solicitudes concurrentes crean dos referencias Bold; una deja de estar asociada',result:'Confirmado con repositorio simulado',distinctReferences:a.boldOrderId!==b.boldOrderId,firstStillMapped:a.boldOrderId===order});
 const {PersonController}=load('server/src/web/rest/person.controller.ts');let userSaved=false,addressDeleted=false;
 const p=new PersonController({save:async()=>{throw new Error('synthetic duplicate document')}},{save:async()=>({id:8}),deleteById:async()=>{addressDeleted=true;}},{registerNewUser:async()=>{userSaved=true;return{id:12}}});
 try{await p.post({user:{login:'admin'},res:{}},{email:'new@example.invalid',fullName:'Synthetic',documentNumber:'duplicate'});}catch{}
 assert(userSaved&&addressDeleted);results.push({test:'Fallo al guardar persona después de crear cuenta',result:'Confirmado: cuenta persistida; solo se compensa dirección',userSaved,addressDeleted});
 const {PageRequest,Page}=load('server/src/domain/base/pagination.entity.ts'),{HeaderUtil}=load('server/src/client/header-util.ts');const headers={};const page=new PageRequest(0,20,'id,ASC');HeaderUtil.addPaginationHeaders({req:{url:'/api/people'},set:(k,v)=>headers[k]=v},new Page([],21,page));assert(headers.Link.includes('page=20'));results.push({test:'21 registros / tamaño 20',expectedLastPage:1,actualLink:headers.Link});
 const {validate}=require('class-validator'),{InvoiceDTO}=load('server/src/service/dto/invoice.dto.ts');const invalid=Object.assign(new InvoiceDTO(),{issueDate:'not-a-date',dueDate:'not-a-date',amountDue:-100,consumptionM3:-5,status:'INVALID',unexpected:'accepted'});const errors=await validate(invalid,{forbidUnknownValues:false});assert.equal(errors.length,0);results.push({test:'DTO factura acepta negativos, fechas y estado inválidos',validationErrors:errors.length,result:'Confirmado con class-validator instalado'});
 const {createI18n}=require('vue-i18n');const translations=JSON.parse(fs.readFileSync(path.join(root,'client/src/i18n/es/settings.json'),'utf8'));const i18n=createI18n({locale:'es',legacy:false,messages:{es:translations}});const html=i18n.global.t('settings.title',{username:'<img src=x onerror="synthetic()">'});results.push({test:'Interpolación de nombre de usuario en traducción HTML',rawHtmlPreserved:html.includes('<img'),result:html.includes('<img')?'Revisar v-html: cadena sin escape':'Escape observado'});
 fs.writeFileSync(path.join(out,'evidencias/probes-resultados.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
})().catch(e=>{console.error(e.stack);process.exitCode=1});
