const {root,out,redact}=require('./audit-tools.cjs'),fs=require('fs'),path=require('path'),ts=require('typescript'),cp=require('child_process');
const ev=path.join(out,'evidencias'), inv=JSON.parse(fs.readFileSync(path.join(ev,'inventario-inicial.json'))),rows=[],routes=[],scripts=[];
function decs(n,sf){return (ts.canHaveDecorators(n)?ts.getDecorators(n):[])?.map(x=>x.expression.getText(sf))??[];}
function at(sf,n){return sf.getLineAndCharacterOfPosition(n.getStart(sf)).line+1;}
for(const p of inv.files){const b=fs.readFileSync(path.join(root,p));const txt=b.toString('utf8'),row={path:p,bytes:b.length,lines:txt.split(/\r?\n/).length,format:path.extname(p),binary:b.includes(0),signals:[]};
 if(!row.binary){for(const [name,re] of Object.entries({html_injection:/v-html|innerHTML|outerHTML|document.write/,dynamic_code:/\beval\(|new Function\(|child_process|execSync\(/,storage:/localStorage|sessionStorage/,empty_catch:/catch\s*(\([^)]*\))?\s*\{\s*\}/,todos:/TODO|FIXME|HACK/,remote_url:/https?:\/\//,accessibility:/aria-|tabindex|role=/,sql:/\.query\(|createQueryBuilder/,test:/\bit\(|\bit.each|\btest\(/})){txt.split(/\r?\n/).forEach((l,i)=>{if(re.test(l))row.signals.push({type:name,line:i+1,text:redact(l).slice(0,250)});});}
 let source=txt;if(p.endsWith('.vue')) {source=[...txt.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');row.scriptExternal=[...txt.matchAll(/<script[^>]*src="([^"]+)"/g)].map(m=>m[1]);row.templateTags=(txt.match(/<[a-z][\w-]*/gi)||[]).length;row.mediaQueries=(txt.match(/@media/g)||[]).length;row.images=(txt.match(/<img\b/g)||[]).length; scripts.push({path:p,script:source});}
 if(/\.(?:[cm]?ts|[cm]?js|vue)$/.test(p)){const sf=ts.createSourceFile(p,source,ts.ScriptTarget.Latest,true);row.syntaxDiagnostics=sf.parseDiagnostics.map(d=>({message:ts.flattenDiagnosticMessageText(d.messageText,' '),start:d.start}));row.declarations=[];ts.forEachChild(sf,function visit(n){if((ts.isClassDeclaration(n)||ts.isFunctionDeclaration(n)||ts.isInterfaceDeclaration(n)||ts.isEnumDeclaration(n))&&n.name)row.declarations.push({name:n.name.getText(sf),line:at(sf,n)});if(ts.isClassDeclaration(n)&&p.includes('/web/rest/')){const dc=decs(n,sf),base=dc.find(d=>d.startsWith('Controller('))?.match(/['"]([^'"]*)['"]/)?.[1]??'';for(const m of n.members){const dm=decs(m,sf),verb=dm.find(d=>/^(Get|Post|PostMethod|Put|Patch|Delete|Sse|Head|Options)\(/.test(d));if(verb){let type=verb.split('(')[0].replace('PostMethod','Post');let route='/'+base+'/'+(verb.match(/['"]([^'"]*)['"]/)?.[1]??'');routes.push({method:type.toUpperCase(),route:route.replace(/\/+/g,'/').replace(/\/$/,''),file:p,line:at(sf,m),handler:m.name?.getText(sf),guards:[...dc,...dm].filter(d=>d.startsWith('UseGuards(')).join('; '),roles:dm.find(d=>d.startsWith('Roles('))??dc.find(d=>d.startsWith('Roles('))??'sin rol específico',params:m.parameters?.map(x=>x.getText(sf)).join('; ')});}}}ts.forEachChild(n,visit);});}
 if(/\.json$/.test(p)&&!p.includes('tsconfig')){try {const j=JSON.parse(txt);row.jsonKeys=Object.keys(j);row.jsonValid=true;}catch{row.jsonValid=false;}}
 if(p.endsWith('.svg'))row.svg={script:/<script/i.test(txt),external:/(?:href|src)=["']https?:/i.test(txt)};
 }rows.push(row);}
fs.writeFileSync(path.join(ev,'analisis-por-archivo.json'),JSON.stringify(rows,null,2));fs.writeFileSync(path.join(ev,'rutas-api.json'),JSON.stringify(routes,null,2));
fs.writeFileSync(path.join(ev,'rutas-api.md'),'# Inventario estático de rutas HTTP\n\nRoles exactos; ROLE_ADMIN no implica ROLE_USER. Webhook valida firma; refresh valida cookie/token. Las rutas de Swagger y Socket.IO se describen en el reporte backend.\n\n| Método | Ruta | Guardas | Roles | Ubicación |\n|---|---|---|---|---|\n'+routes.map(r=>`| ${r.method} | ${r.route} | ${r.guards||'Sin guarda JWT'} | ${r.roles} | ${r.file}:${r.line} |`).join('\n'));
const lock=JSON.parse(fs.readFileSync(path.join(root,'package-lock.json'))),deps=Object.entries(lock.packages).map(([p,v])=>({path:p,name:v.name||p.split('node_modules/').pop(),version:v.version,license:v.license??'No declarada',dev:!!v.dev,optional:!!v.optional,deprecated:v.deprecated,integrity:!!v.integrity}));
fs.writeFileSync(path.join(ev,'dependencias-lock.json'),JSON.stringify(deps,null,2));
fs.writeFileSync(path.join(ev,'dependencias-lock.csv'),'ruta,nombre,version,licencia,desarrollo,opcional,obsoleta\n'+deps.map(d=>[d.path,d.name,d.version,d.license,d.dev,d.optional,d.deprecated??''].map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'));
fs.writeFileSync(path.join(ev,'scripts-vue.json'),JSON.stringify(scripts,null,2));
console.log(JSON.stringify({files:rows.length,routes:routes.length,lockEntries:deps.length,licencias:[...new Set(deps.map(d=>d.license))],deprecated:deps.filter(d=>d.deprecated).map(d=>({name:d.name,version:d.version,reason:d.deprecated})),vueInline:scripts.filter(s=>s.script.trim()).map(s=>({path:s.path,lines:s.script.split('\n').length})),signals:rows.filter(r=>r.signals.some(s=>s.type==='html_injection')).map(r=>({path:r.path,signals:r.signals.filter(s=>s.type==='html_injection')}))},null,2));
